baseURL = 'https://woxqaq.github.io/'
languageCode = 'zh-cn'
defaultContentLanguage = "zh"
title = 'woxQAQ blog'
# copyright = "本站遵循 CC BY-NC-SA 4.0 协议"
theme = 'loveit'
enableEmoji = true

[caches]
[caches.images]
dir = ':cacheDir/images'

[[menu.main]]
url = "/home"
name = "主页"
weight = 0

[[menu.main]]
url = "/posts"
name = "归档"
weight = 1

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[sitemap]
changeFreq = ''
filename = 'sitemap.xml'
priority = -1

[params]
# enableLaTeX = true
# github = "woxQAQ"
# email = "woxqaq@gmail.com"
# lastmod = true
# location = "China"
# headerIcon = "https://avatars.githubusercontent.com/u/53343562?s=96&v=4"
# avatar = "https://avatars.githubusercontent.com/u/53343562?s=400&u=f72da4c3be00fb20631e0804897cc81bfa23bcb4&v=4"
gitRepo = ""
defaultTheme = "auto"
title = "woxQAQ World"
description = "woxQAQ personal world"

[params.author]
name = "woxQAQ"
email = "woxqaq@gmail.com"
link = "https://github.com/woxQAQ"

[params.header]
desktopMode = "fixed"
mobileMode = "auto"
[params.header.title]
name = "woxQAQ World"

[params.footer]
copyright = true
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
hugo = true

[params.page]
hiddenFromHomePage = false
hiddenFromSearch = false
twemoji = false
lightgallery = false
ruby = true
fraction = true
linkToMarkdown = true
seriesNavigation = true
