baseURL = 'https://woxqaq.github.io/'
languageCode = 'zh-cn'
defaultContentLanguage = "zh"
title = 'woxQAQ blog'
copytight = "本站遵循 CC BY-NC-SA 4.0 协议"
theme = 'github-style'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
url = "/home"
name = "主页"
weight = 0

[[menu.main]]
url = "/posts"
name = "归档"
weight = 1

[params]
enableLaTeX = true
github = "woxQAQ"
email = "woxqaq@gmail.com"
lastmod = true
location= "China"