baseURL = 'https://woxqaq.github.io/'
languageCode = 'zh-cn'
defaultContentLanguage = "zh"
title = 'woxQAQ blog'
copyright = "本站遵循 CC BY-NC-SA 4.0 协议"
theme = 'github-style'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
url = "/home"
name = "主页"
weight = 0

[[menu.main]]
url = "/posts"
name = "归档"
weight = 1

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1
  
[params]
enableLaTeX = true
github = "woxQAQ"
email = "woxqaq@gmail.com"
lastmod = true
location= "China"
headerIcon = "https://avatars.githubusercontent.com/u/53343562?s=96&v=4"
avatar = "https://avatars.githubusercontent.com/u/53343562?s=400&u=f72da4c3be00fb20631e0804897cc81bfa23bcb4&v=4"