baseURL = 'https://woxqaq.github.io/'
languageCode = 'zh-CN'
title = 'woxQAQ blog'
copytight = "本站遵循 CC BY-NC-SA 4.0 协议"
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
url = "/posts"
name = "归档"
weight = 1

[params]
enableLaTeX = true
