name: Deploy Astro site to Github Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with: 
          fetch-depth: 0
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build
        run: pnpm build

  deploy:
    needs: Build-and-Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
        id: deployment
